### ISSUE TITLE
Pressing on enter after search reloads the page with all projects visible

### ISSUE THREAD

**Issue by agraebe** [SAP/sap.github.com#5]

**Comment by sunilkumarc** [comment]
Hi @agraebe ,

I would like to work on this bug. Can you help me proceeding with this ?

Thanks,
Sunil

**Comment by agraebe** [comment]
@sunilkumarc I just pushed an update to solve this. Basically it'll override the std behavior of the form and simply return false on submit/return.

**Comment by sunilkumarc** [comment]
:+1:
