### ISSUE TITLE
domain name

### ISSUE THREAD

**Issue by thojansen** [SAP/sap.github.com#7]
- should the repo be renamed to sap.github.io?
- did you already check for github.sap?

**Comment by agraebe** [comment]
This page is reachable via sap.github.com and .io, so the repo name change is not adding valuable information to the users. As for github.sap - that would imply we would buy another domain, whereas right now we're using the complementary .gihub.com/.github.io domains.. I don't know if there will be a benefit by buying another TLD... Or am I missing something?

**Comment by thojansen** [comment]
i know that both domains work, but its not very consistent :confused: 
"Web page content for the sap.github.com - http://sap.github.io"

sap owns the tld since a few days

**Comment by agraebe** [comment]
Now it's more consistent. If you know a contact person for the .sap domain, please PM me. Thanks!
